services:
  fastify:
    build: .
    container_name: fastify
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/modsecurity:/etc/nginx/modsec:ro
