#!/bin/sh
set -e

CERT_PATH="/etc/nginx/certs/pong.localhost.crt"
KEY_PATH="/etc/nginx/certs/pong.localhost.key"

echo "Waiting for certificate and key to be generated by Vault..."

while [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; do
  sleep 2
done

echo "Certificate and key found. Starting Nginx..."
exec nginx -g 'daemon off;'